# Generated by Django 4.2.11 on 2025-04-28 19:03

from django.db import migrations, models
import tasks.models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, validators=[tasks.models.date_validation]),
        ),
    ]
