# Generated by Django 4.2.11 on 2025-04-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='when_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
