# Generated by Django 4.2.11 on 2025-04-30 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_when_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='when_completed',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 4, 30, 17, 24, 11, 405463, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
