# Generated by Django 4.2.11 on 2025-04-30 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_when_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='when_completed',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 4, 30, 17, 26, 26, 660137, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
