# Generated by Django 4.2.11 on 2025-04-30 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_category_remove_task_when_completed_task_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='when_completed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
